sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t sparkubuntu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sparkubuntu/react-test npm run test

after_success:
  # Build all the project images
  - docker build -t sparkubuntu/multi-client ./client
  - docker build -t sparkubuntu/multi-nginx ./nginx
  - docker build -t sparkubuntu/multi-server ./server
  - docker build -t sparkubuntu/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take custom build images and push them to docker hub
  - docker push sparkubuntu/multi-client
  - docker push sparkubuntu/multi-nginx
  - docker push sparkubuntu/multi-server
  - docker push sparkubuntu/multi-worker